{
 "title": "antenna",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "antenna_latitude", "label": "Antenna Latitude" },
   { "name": "antenna_longitude", "label": "Antenna Longitude" },
   { "name": "antenna_altitude", "label": "Antenna Altitude" }
  ]
 },
 "panels": [
  {
   "title": "Azimuth (Data Manager WiFi Bridge)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\n// Dashboard-Variablen\r\nantennaLat = float(v: ${antenna_latitude})\r\nantennaLon = float(v: ${antenna_longitude})\r\nantennaAlt = float(v: ${antenna_altitude})\r\n\r\n// Radius der Erde in Metern\r\nR = 6371000.0\r\n\r\n// Umrechnung von Grad in Radianten\r\ndegToRad = (d) => d * math.pi / 180.0\r\n\r\nfrom(bucket: \"balloon\")\r\n  |> range(start: -90d)\r\n  |> filter(fn: (r) => r._measurement == \"dm_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => exists r.latitude and exists r.longitude and exists r.altitude) // Filtern von ungültigen Werten\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      balloonLat: r.latitude,\r\n      balloonLon: r.longitude,\r\n      balloonAlt: r.altitude,\r\n      deltaPhi: degToRad(d: r.latitude - antennaLat),\r\n      deltaLambda: degToRad(d: r.longitude - antennaLon),\r\n      phi1: degToRad(d: antennaLat),\r\n      phi2: degToRad(d: r.latitude)\r\n  }))\r\n  |> map(fn: (r) => {\r\n      a = math.sin(x: r.deltaPhi / 2.0) * math.sin(x: r.deltaPhi / 2.0) + \r\n          math.cos(x: r.phi1) * math.cos(x: r.phi2) * \r\n          math.sin(x: r.deltaLambda / 2.0) * math.sin(x: r.deltaLambda / 2.0)\r\n      distance = R * 2.0 * math.atan2(y: math.sqrt(x: a), x: math.sqrt(x: 1.0 - a))\r\n      return {\r\n        r with\r\n        a: a,\r\n        distance: distance\r\n      }\r\n  })\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      azimuth: math.atan2(y: math.sin(x: r.deltaLambda) * math.cos(x: r.phi2),\r\n                         x: math.cos(x: r.phi1) * math.sin(x: r.phi2) - math.sin(x: r.phi1) * math.cos(x: r.phi2) * math.cos(x: r.deltaLambda)) * 180.0 / math.pi,\r\n      horizontalDistance: r.distance,\r\n      elevation: math.atan2(y: float(v: r.balloonAlt - antennaAlt), x: r.distance) * 180.0 / math.pi\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      azimuth: if r.azimuth < 0.0 then r.azimuth + 360.0 else r.azimuth,\r\n      elevation: r.elevation\r\n  }))\r\n  |> keep(columns: [\"_time\", \"azimuth\"])\r\n  |> yield(name: \"angles\")\r\n"
    }
   ]
  },
  {
   "title": "Elevation (Data Manager WiFi Bridge)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\n// Dashboard-Variablen\r\nantennaLat = float(v: ${antenna_latitude})\r\nantennaLon = float(v: ${antenna_longitude})\r\nantennaAlt = float(v: ${antenna_altitude})\r\n\r\n// Radius der Erde in Metern\r\nR = 6371000.0\r\n\r\n// Umrechnung von Grad in Radianten\r\ndegToRad = (d) => d * math.pi / 180.0\r\n\r\nfrom(bucket: \"balloon\")\r\n  |> range(start: -90d)\r\n  |> filter(fn: (r) => r._measurement == \"dm_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => exists r.latitude and exists r.longitude and exists r.altitude) // Filtern von ungültigen Werten\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      balloonLat: r.latitude,\r\n      balloonLon: r.longitude,\r\n      balloonAlt: r.altitude,\r\n      deltaPhi: degToRad(d: r.latitude - antennaLat),\r\n      deltaLambda: degToRad(d: r.longitude - antennaLon),\r\n      phi1: degToRad(d: antennaLat),\r\n      phi2: degToRad(d: r.latitude)\r\n  }))\r\n  |> map(fn: (r) => {\r\n      a = math.sin(x: r.deltaPhi / 2.0) * math.sin(x: r.deltaPhi / 2.0) + \r\n          math.cos(x: r.phi1) * math.cos(x: r.phi2) * \r\n          math.sin(x: r.deltaLambda / 2.0) * math.sin(x: r.deltaLambda / 2.0)\r\n      distance = R * 2.0 * math.atan2(y: math.sqrt(x: a), x: math.sqrt(x: 1.0 - a))\r\n      return {\r\n        r with\r\n        a: a,\r\n        distance: distance\r\n      }\r\n  })\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      azimuth: math.atan2(y: math.sin(x: r.deltaLambda) * math.cos(x: r.phi2),\r\n                         x: math.cos(x: r.phi1) * math.sin(x: r.phi2) - math.sin(x: r.phi1) * math.cos(x: r.phi2) * math.cos(x: r.deltaLambda)) * 180.0 / math.pi,\r\n      horizontalDistance: r.distance,\r\n      elevation: math.atan2(y: float(v: r.balloonAlt - antennaAlt), x: r.distance) * 180.0 / math.pi\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      azimuth: if r.azimuth < 0.0 then r.azimuth + 360.0 else r.azimuth,\r\n      elevation: r.elevation\r\n  }))\r\n  |> keep(columns: [\"_time\", \"elevation\"])\r\n  |> yield(name: \"angles\")\r\n"
    }
   ]
  },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aprs_gps",
     "query": "from(bucket: \"balloon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"aprs_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.latitude != 0 and r.longitude != 0)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      latitude: r.latitude,\r\n      longitude: r.longitude\r\n  }))\r\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\"])\r\n  |> yield(name: \"aprs\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aprs_gps",
     "query": "from(bucket: \"balloon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dm_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.latitude != 0 and r.longitude != 0)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      latitude: r.latitude,\r\n      longitide: r.longitude\r\n  }))\r\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\"])\r\n  |> yield(name: \"dm\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aprs_gps",
     "query": "from(bucket: \"balloon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spot_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.latitude != 0 and r.longitude != 0)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      latitude: r.latitude,\r\n      longitude: r.longitude\r\n  }))\r\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\"])\r\n  |> yield(name: \"spot\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aprs_gps",
     "query": "from(bucket: \"balloon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dm_system\")\r\n  |> limit(n: 1)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      latitude: float(v: ${antenna_latitude}),\r\n      longitude: float(v: ${antenna_longitude})\r\n  }))\r\n  |> keep(columns: [\"latitude\", \"longitude\"])\r\n  |> yield(name: \"antenna\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Azimuth (APRS)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\n// Dashboard-Variablen\r\nantennaLat = float(v: ${antenna_latitude})\r\nantennaLon = float(v: ${antenna_longitude})\r\nantennaAlt = int(v: ${antenna_altitude})\r\n\r\n// Radius der Erde in Metern\r\nR = 6371000.0\r\n\r\n// Umrechnung von Grad in Radianten\r\ndegToRad = (d) => d * math.pi / 180.0\r\n\r\nfrom(bucket: \"balloon\")\r\n  |> range(start: -90d)\r\n  |> filter(fn: (r) => r._measurement == \"aprs_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => exists r.latitude and exists r.longitude and exists r.altitude) // Filtern von ungültigen Werten\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      balloonLat: r.latitude,\r\n      balloonLon: r.longitude,\r\n      balloonAlt: r.altitude,\r\n      deltaPhi: degToRad(d: r.latitude - antennaLat),\r\n      deltaLambda: degToRad(d: r.longitude - antennaLon),\r\n      phi1: degToRad(d: antennaLat),\r\n      phi2: degToRad(d: r.latitude)\r\n  }))\r\n  |> map(fn: (r) => {\r\n      a = math.sin(x: r.deltaPhi / 2.0) * math.sin(x: r.deltaPhi / 2.0) + \r\n          math.cos(x: r.phi1) * math.cos(x: r.phi2) * \r\n          math.sin(x: r.deltaLambda / 2.0) * math.sin(x: r.deltaLambda / 2.0)\r\n      distance = R * 2.0 * math.atan2(y: math.sqrt(x: a), x: math.sqrt(x: 1.0 - a))\r\n      return {\r\n        r with\r\n        a: a,\r\n        distance: distance\r\n      }\r\n  })\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      azimuth: math.atan2(y: math.sin(x: r.deltaLambda) * math.cos(x: r.phi2),\r\n                         x: math.cos(x: r.phi1) * math.sin(x: r.phi2) - math.sin(x: r.phi1) * math.cos(x: r.phi2) * math.cos(x: r.deltaLambda)) * 180.0 / math.pi,\r\n      horizontalDistance: r.distance,\r\n      elevation: math.atan2(y: float(v: r.balloonAlt - antennaAlt), x: r.distance) * 180.0 / math.pi\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      azimuth: if r.azimuth < 0.0 then r.azimuth + 360.0 else r.azimuth,\r\n      elevation: r.elevation\r\n  }))\r\n  |> keep(columns: [\"_time\", \"azimuth\"])\r\n  |> yield(name: \"angles\")\r\n"
    }
   ]
  },
  {
   "title": "Elevation (APRS)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\n// Dashboard-Variablen\r\nantennaLat = float(v: ${antenna_latitude})\r\nantennaLon = float(v: ${antenna_longitude})\r\nantennaAlt = int(v: ${antenna_altitude})\r\n\r\n// Radius der Erde in Metern\r\nR = 6371000.0\r\n\r\n// Umrechnung von Grad in Radianten\r\ndegToRad = (d) => d * math.pi / 180.0\r\n\r\nfrom(bucket: \"balloon\")\r\n  |> range(start: -90d)\r\n  |> filter(fn: (r) => r._measurement == \"aprs_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => exists r.latitude and exists r.longitude and exists r.altitude) // Filtern von ungültigen Werten\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      balloonLat: r.latitude,\r\n      balloonLon: r.longitude,\r\n      balloonAlt: r.altitude,\r\n      deltaPhi: degToRad(d: r.latitude - antennaLat),\r\n      deltaLambda: degToRad(d: r.longitude - antennaLon),\r\n      phi1: degToRad(d: antennaLat),\r\n      phi2: degToRad(d: r.latitude)\r\n  }))\r\n  |> map(fn: (r) => {\r\n      a = math.sin(x: r.deltaPhi / 2.0) * math.sin(x: r.deltaPhi / 2.0) + \r\n          math.cos(x: r.phi1) * math.cos(x: r.phi2) * \r\n          math.sin(x: r.deltaLambda / 2.0) * math.sin(x: r.deltaLambda / 2.0)\r\n      distance = R * 2.0 * math.atan2(y: math.sqrt(x: a), x: math.sqrt(x: 1.0 - a))\r\n      return {\r\n        r with\r\n        a: a,\r\n        distance: distance\r\n      }\r\n  })\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      azimuth: math.atan2(y: math.sin(x: r.deltaLambda) * math.cos(x: r.phi2),\r\n                         x: math.cos(x: r.phi1) * math.sin(x: r.phi2) - math.sin(x: r.phi1) * math.cos(x: r.phi2) * math.cos(x: r.deltaLambda)) * 180.0 / math.pi,\r\n      horizontalDistance: r.distance,\r\n      elevation: math.atan2(y: float(v: r.balloonAlt - antennaAlt), x: r.distance) * 180.0 / math.pi\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      azimuth: if r.azimuth < 0.0 then r.azimuth + 360.0 else r.azimuth,\r\n      elevation: r.elevation\r\n  }))\r\n  |> keep(columns: [\"_time\", \"elevation\"])\r\n  |> yield(name: \"angles\")\r\n"
    }
   ]
  },
  {
   "title": "Azimuth (SPOT Trace)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"math\"\n\n// Dashboard-Variablen\nantennaLat = float(v: ${antenna_latitude})\nantennaLon = float(v: ${antenna_longitude})\nantennaAlt = float(v: ${antenna_altitude})\n\n// Radius der Erde in Metern\nR = 6371000.0\n\n// Umrechnung von Grad in Radianten\ndegToRad = (d) => d * math.pi / 180.0\n\nfrom(bucket: \"balloon\")\n  |> range(start: -90d)\n  |> filter(fn: (r) => r._measurement == \"spot_gps\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => exists r.latitude and exists r.longitude and exists r.altitude) // Filtern von ungültigen Werten\n  |> map(fn: (r) => ({\n      r with\n      balloonLat: r.latitude,\n      balloonLon: r.longitude,\n      balloonAlt: r.altitude,\n      deltaPhi: degToRad(d: r.latitude - antennaLat),\n      deltaLambda: degToRad(d: r.longitude - antennaLon),\n      phi1: degToRad(d: antennaLat),\n      phi2: degToRad(d: r.latitude)\n  }))\n  |> map(fn: (r) => {\n      a = math.sin(x: r.deltaPhi / 2.0) * math.sin(x: r.deltaPhi / 2.0) + \n          math.cos(x: r.phi1) * math.cos(x: r.phi2) * \n          math.sin(x: r.deltaLambda / 2.0) * math.sin(x: r.deltaLambda / 2.0)\n      distance = R * 2.0 * math.atan2(y: math.sqrt(x: a), x: math.sqrt(x: 1.0 - a))\n      return {\n        r with\n        a: a,\n        distance: distance\n      }\n  })\n  |> map(fn: (r) => ({\n      r with\n      azimuth: math.atan2(y: math.sin(x: r.deltaLambda) * math.cos(x: r.phi2),\n                         x: math.cos(x: r.phi1) * math.sin(x: r.phi2) - math.sin(x: r.phi1) * math.cos(x: r.phi2) * math.cos(x: r.deltaLambda)) * 180.0 / math.pi,\n      horizontalDistance: r.distance,\n      elevation: math.atan2(y: r.balloonAlt - antennaAlt, x: r.distance) * 180.0 / math.pi\n  }))\n  |> map(fn: (r) => ({\n      r with\n      azimuth: if r.azimuth < 0.0 then r.azimuth + 360.0 else r.azimuth,\n      elevation: r.elevation\n  }))\n  |> keep(columns: [\"_time\", \"azimuth\"])\n  |> yield(name: \"angles\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elevation (SPOT Trace)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\n// Dashboard-Variablen\r\nantennaLat = float(v: ${antenna_latitude})\r\nantennaLon = float(v: ${antenna_longitude})\r\nantennaAlt = float(v: ${antenna_altitude})\r\n\r\n// Radius der Erde in Metern\r\nR = 6371000.0\r\n\r\n// Umrechnung von Grad in Radianten\r\ndegToRad = (d) => d * math.pi / 180.0\r\n\r\nfrom(bucket: \"balloon\")\r\n  |> range(start: -90d)\r\n  |> filter(fn: (r) => r._measurement == \"spot_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => exists r.latitude and exists r.longitude and exists r.altitude) // Filtern von ungültigen Werten\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      balloonLat: r.latitude,\r\n      balloonLon: r.longitude,\r\n      balloonAlt: r.altitude,\r\n      deltaPhi: degToRad(d: r.latitude - antennaLat),\r\n      deltaLambda: degToRad(d: r.longitude - antennaLon),\r\n      phi1: degToRad(d: antennaLat),\r\n      phi2: degToRad(d: r.latitude)\r\n  }))\r\n  |> map(fn: (r) => {\r\n      a = math.sin(x: r.deltaPhi / 2.0) * math.sin(x: r.deltaPhi / 2.0) + \r\n          math.cos(x: r.phi1) * math.cos(x: r.phi2) * \r\n          math.sin(x: r.deltaLambda / 2.0) * math.sin(x: r.deltaLambda / 2.0)\r\n      distance = R * 2.0 * math.atan2(y: math.sqrt(x: a), x: math.sqrt(x: 1.0 - a))\r\n      return {\r\n        r with\r\n        a: a,\r\n        distance: distance\r\n      }\r\n  })\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      azimuth: math.atan2(y: math.sin(x: r.deltaLambda) * math.cos(x: r.phi2),\r\n                         x: math.cos(x: r.phi1) * math.sin(x: r.phi2) - math.sin(x: r.phi1) * math.cos(x: r.phi2) * math.cos(x: r.deltaLambda)) * 180.0 / math.pi,\r\n      horizontalDistance: r.distance,\r\n      elevation: math.atan2(y: r.balloonAlt - antennaAlt, x: r.distance) * 180.0 / math.pi\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      azimuth: if r.azimuth < 0.0 then r.azimuth + 360.0 else r.azimuth,\r\n      elevation: r.elevation\r\n  }))\r\n  |> keep(columns: [\"_time\", \"elevation\"])\r\n  |> yield(name: \"angles\")\r\n"
    }
   ]
  }
 ]
}