{
 "title": "monitor",
 "time": { "from": "now-4h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "antenna_latitude", "label": "Antenna Latitude", "query": "47.559647" },
   { "name": "antenna_longitude", "label": "Antenna Longitude", "query": "9.698356" },
   { "name": "antenna_altitude", "label": "Antenna Altitude", "query": "406" }
  ]
 },
 "panels": [
  {
   "title": "Out Temp (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"temp\") FROM \"wifi_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"temp\") FROM \"wifi_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS",
     "query": "SELECT mean(\"temp\") FROM \"aprs_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File",
     "query": "SELECT mean(\"temp\") FROM \"file_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "WiFi Magnet",
     "query": "SELECT mean(\"temp\") FROM \"wifi_magnet\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File Magnet",
     "query": "SELECT mean(\"temp\") FROM \"file_magnet\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Humidity (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"humidity\") FROM \"wifi_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"humidity\") FROM \"wifi_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS",
     "query": "SELECT mean(\"humidity\") FROM \"aprs_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File",
     "query": "SELECT mean(\"humidity\") FROM \"file_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 24, "w": 10, "x": 14, "y": 0 },
   "options": {
    "content": "<style>\n.video-container {\n  width: 100%;\n  aspect-ratio: 16 / 9;\n}\n\n.video {\n  width: 100%;\n  height: 100%;\n}\n</style>\n\n<div class=\"video-container\">\n  <iframe class=\"video\" src=\"https://www.youtube.com/embed/4Naa59Qais0?autoplay=true\" title=\"Mission Teaser | Space Balloon | Bodensee-Gymnasium Lindau\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\n</div>"
   }
  },
  {
   "title": "Out Temp (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"temp\") FROM \"aprs_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"humidity\") FROM \"aprs_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thermal Cam",
   "type": "text",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "options": {
    "content": "<style>\n.image-thermal {\n  width: 100%;\n  aspect-ratio: 4 / 3;\n}\n</style>\n\n<iframe class=\"image-thermal\" src=\"https://sm.balloon.nikogenia.de/image/thermal\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\n"
   }
  },
  {
   "title": "Inside Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "WiFi Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"min\") FROM \"wifi_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "WiFi Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"avg\") FROM \"wifi_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "WiFi Median",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"median\") FROM \"wifi_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "WiFi Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"max\") FROM \"wifi_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS Min",
     "query": "SELECT mean(\"min\") FROM \"aprs_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "APRS Average",
     "query": "SELECT mean(\"avg\") FROM \"aprs_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "APRS Median",
     "query": "SELECT mean(\"median\") FROM \"aprs_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "APRS Max",
     "query": "SELECT mean(\"max\") FROM \"aprs_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File",
     "query": "SELECT mean(\"min\"), mean(\"avg\"), mean(\"median\"), mean(\"max\") FROM \"file_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Pressure (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"pressure\") FROM \"wifi_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"pressure\") FROM \"wifi_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS",
     "query": "SELECT mean(\"pressure\") FROM \"aprs_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File",
     "query": "SELECT mean(\"pressure\") FROM \"file_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Pressure (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"pressure\") FROM \"aprs_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Temp Min (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"min\") FROM \"wifi_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Temp Avg (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"avg\") FROM \"wifi_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Temp Max (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"max\") FROM \"wifi_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO₂ (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"co2\") FROM \"wifi_co2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO₂",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"co2\") FROM \"wifi_co2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT mean(\"co2\") FROM \"aprs_co2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT mean(\"co2\") FROM \"file_co2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "In Temp Min (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"min\") FROM \"aprs_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Temp Avg (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"avg\") FROM \"aprs_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Temp Max (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"max\") FROM \"aprs_thermal\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO₂ (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"co2\") FROM \"aprs_co2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UV (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mW/cm²" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"uv\") FROM \"wifi_adc\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UV",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mW/cm²" } },
   "targets": [
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"uv\") FROM \"wifi_adc\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS",
     "query": "SELECT mean(\"uv\") FROM \"aprs_adc\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File",
     "query": "SELECT mean(\"uv\") FROM \"file_adc\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "VOC (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "g/l" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"voc\") FROM \"wifi_co2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "g/l" } },
   "targets": [
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"voc\") FROM \"wifi_co2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS",
     "query": "SELECT mean(\"voc\") FROM \"aprs_co2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File",
     "query": "SELECT mean(\"voc\") FROM \"file_co2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "UV (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mW/cm²" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"uv\") FROM \"aprs_adc\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VOC (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "g/l" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"voc\") FROM \"aprs_co2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU (WiFi)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_system",
     "query": "SELECT mean(\"cpu\") FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"cpu\") FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"cpu\") FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "File",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"cpu\") FROM \"file_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU (APRS)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_system",
     "query": "SELECT mean(\"cpu\") FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Sent (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"sent\") FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "WiFi Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"sent\") FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS Sent",
     "query": "SELECT mean(\"sent\") FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File Sent",
     "query": "SELECT mean(\"sent\") FROM \"file_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "WiFi Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"received\") FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS Received",
     "query": "SELECT mean(\"received\") FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File Received",
     "query": "SELECT mean(\"received\") FROM \"file_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"balloon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"aprs_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.latitude != 0 and r.longitude != 0)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      latitude: r.latitude,\r\n      longitude: r.longitude,\r\n      altitude: r.altitude\r\n  }))\r\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\", \"altitude\"])\r\n  |> yield(name: \"aprs\")"
    },
    {
     "query": "from(bucket: \"balloon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.latitude != 0 and r.longitude != 0)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      latitude: r.latitude,\r\n      longitide: r.longitude,\r\n      altitude: r.altitude\r\n  }))\r\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\", \"altitude\"])\r\n  |> yield(name: \"wifi\")"
    },
    {
     "query": "from(bucket: \"balloon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spot_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.latitude != 0 and r.longitude != 0)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      latitude: r.latitude,\r\n      longitude: r.longitude,\r\n      altitude: r.altitude\r\n  }))\r\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\", \"altitude\"])\r\n  |> yield(name: \"spot\")"
    },
    {
     "query": "from(bucket: \"balloon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"aprs_pico\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.latitude != 0 and r.longitude != 0)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      latitude: r.latitude,\r\n      longitude: r.longitude,\r\n      altitude: r.altitude\r\n  }))\r\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\", \"altitude\"])\r\n  |> yield(name: \"pico\")\r\n"
    },
    {
     "query": "from(bucket: \"balloon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"file_gps\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.latitude != 0 and r.longitude != 0)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      latitude: r.latitude,\r\n      longitude: r.longitude,\r\n      altitude: r.altitude\r\n  }))\r\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\", \"altitude\"])\r\n  |> yield(name: \"file\")\r\n"
    },
    {
     "query": "from(bucket: \"balloon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => true)\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      latitude: float(v: ${antenna_latitude}),\r\n      longitude: float(v: ${antenna_longitude}),\r\n      altitude: float(v: ${antenna_altitude})\r\n  }))\r\n  |> keep(columns: [\"latitude\", \"longitude\", \"altitude\"])\r\n  |> yield(name: \"antenna\")\r\n  "
    }
   ]
  },
  {
   "title": "Net Received (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"received\") FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM (WiFi)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_system",
     "query": "SELECT mean(\"memory\") FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"memory\") FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"memory\") FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "File",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"memory\") FROM \"file_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM (APRS)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_system",
     "query": "SELECT mean(\"memory\") FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Sent (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"sent\") FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "WiFi Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT * FROM (SELECT DERIVATIVE(mean(\"sent\"), 1s) AS \"rate\" FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) WHERE \"rate\" > 0",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT * FROM (SELECT DERIVATIVE(mean(\"sent\"), 1s) AS \"rate\" FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) WHERE \"rate\" > 0",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "WiFi Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT * FROM (SELECT DERIVATIVE(mean(\"received\"), 1s) AS \"rate\" FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) WHERE \"rate\" > 0",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT * FROM (SELECT DERIVATIVE(mean(\"received\"), 1s) AS \"rate\" FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) WHERE \"rate\" > 0",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "File Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT * FROM (SELECT DERIVATIVE(mean(\"sent\"), 1s) AS \"rate\" FROM \"file_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) WHERE \"rate\" > 0",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "File Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT * FROM (SELECT DERIVATIVE(mean(\"received\"), 1s) AS \"rate\" FROM \"file_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) WHERE \"rate\" > 0",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Received (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"received\") FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sys Temp (WiFi)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_system",
     "query": "SELECT mean(\"temp\") FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"temp\") FROM \"wifi_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"temp\") FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "File",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"temp\") FROM \"file_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sys Temp (APRS)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_system",
     "query": "SELECT mean(\"temp\") FROM \"aprs_system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cooling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT last(\"cool\") FROM \"wifi_datamanager\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cooling",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT last(\"cool\") FROM \"wifi_datamanager\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "File",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT last(\"cool\") FROM \"file_datamanager\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "wifi", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Live (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 2, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "wifi", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Video 0 (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 3, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "wifi", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Video 1 (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 4, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "wifi", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Video 2 (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 5, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "wifi", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Alive Services (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "wifi", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Dead Services (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "wifi", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "sm", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Uptime (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "aprs", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Live (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 2, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "aprs", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Video 0 (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 3, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "aprs", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Video 1 (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 4, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "aprs", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Video 2 (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 5, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "aprs", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Alive Services (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "aprs", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Dead Services (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "aprs", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Subtitle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "sm", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Altitude (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"altitude\") FROM \"wifi_gps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Altitude (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"altitude\") FROM \"aprs_gps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Altitude (PicoAPRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"altitude\") FROM \"aprs_pico\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alt Climate (WiFi)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"altitude\") FROM \"wifi_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alt Climate (APRS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"altitude\") FROM \"aprs_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(paths_bytes_received - paths_bytes_received offset 10s) / 10",
     "legendFormat": "recv {{name}}"
    },
    {
     "expr": "(paths_bytes_sent - paths_bytes_sent offset 10s) / 10",
     "legendFormat": "sent {{name}}"
    }
   ]
  },
  {
   "title": "Phase",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "sm", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Source Connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "sm", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Countdown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "sm", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_climate",
     "query": "SELECT mean(\"altitude\") FROM \"wifi_gps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "APRS",
     "query": "SELECT mean(\"altitude\") FROM \"aprs_gps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PicoAPRS",
     "query": "SELECT mean(\"altitude\") FROM \"aprs_pico\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "SPOT Trace",
     "query": "SELECT mean(\"altitude\") FROM \"spot_gps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File",
     "query": "SELECT mean(\"altitude\") FROM \"file_gps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "File Climate",
     "query": "SELECT mean(\"altitude\") FROM \"file_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "WiFi Climate",
     "query": "SELECT mean(\"altitude\") FROM \"wifi_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "APRS Climate",
     "query": "SELECT mean(\"altitude\") FROM \"aprs_climate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Sensor Display",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "sm", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Source Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "sm", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Stream Countdown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "global_query_id": "sm", "source": "url", "type": "global", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Receive Signal Strength",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"rx_signal\") FROM \"wifi_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transmit Signal Strength",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 1, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"tx_signal\") FROM \"wifi_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "RX Signal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "rx_signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RX Signal Antenna 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "rx_signal_a0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RX Signal Antenna 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "rx_signal_a1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TX Signal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "tx_signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TX Signal Antenna 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "tx_signal_a0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TX Signal Antenna 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "tx_signal_a1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Receive Quality",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"rx_quality\") FROM \"wifi_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transmit Quality",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"tx_quality\") FROM \"wifi_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quality",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "TX Quality",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "rx_quality" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RX Quality",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "tx_quality" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"rx_bytes\") FROM \"wifi_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 13, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"tx_bytes\") FROM \"wifi_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "TX Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RX Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"uptime\") FROM \"wifi_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Signal to Noise",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 19, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dm_magnet",
     "query": "SELECT mean(\"noise\") FROM \"wifi_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Signal to Noise",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_stats",
     "select": [
      [
       { "params": [ "noise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}